### ISSUE TITLE
what makes dist-keras different?

### ISSUE THREAD

**Issue by MalcolmSun** [JoeriHermans/dist-keras#3]
Hi, I'm interested in this project. I have a question, what's the difference between disk-keras and elephas another project which is also built with spark and keras?

**Comment by JoeriHermans** [comment]
Hi Malcolm,

Basically, when I started developing this project Elephas did not support Keras 1.0+. However, Elephas only supports a DOWNPOUR-like algorithm, and it is very difficult to add other distributed optimizers without some amount of code. Furthermore, after the Keras 1.0+ patch of Elephas, I tried to run it on our cluster in order to compare the performance with dist-keras, however, I was not able to run one of the examples (I posted an issue regarding this). Also, Elephas is not compatiable with Spark 2.0, whereas dist-keras is.

I hope this was sufficient. If you have any other questions, feel free to ask them.

**Comment by MalcolmSun** [comment]
Thanks. I am looking forward to your future work.
