### ISSUE TITLE
Will distributed.py become available?

### ISSUE THREAD

**Issue by verarim** [JoeriHermans/dist-keras#6]
Hello!

I'm trying to run data_preprocessing.ipynb and analysis.ipynb examples, but distributed.py is not available. Namely, method LabelVectorTransformer is missing. Will this import be back? Is there some temporary solution I could use to run these python notebooks?

Regards,
Vera

**Comment by JoeriHermans** [comment]
Hi Vera

Sorry, this is probably a mistake on my part when merging with master. I suggest using the development branch for now since I'm updating some mechanisms to improve performance. I think I will have everything "production"-ready by next week. After that you can use master :) 

However, if you would like to use the master branch right now, you can just remove distributed.py and use the transformers.py import.

I hope this helps. Let me know!

Kind regards,

Joeri

**Comment by verarim** [comment]
Thanks, Joeri.

Your answer helped me to fix the imports, however, analysis.ipynb  still does not run out-of-the-box (for example, exception occurs when a "predicted_index" column is not found during evaluation, it has to be "prediction_index", I suppose).

I'd better get back to it next week then.

Good luck on updating, thanks for your work!
Vera

**Comment by JoeriHermans** [comment]
Sorry! I will make sure the examples run correctly!

Joeri

**Comment by JoeriHermans** [comment]
Hi Vera,

I pushed the new code, examples, and documentation to master. If you encounter any problems, feel free to open a new issue.
